<!--====== Javascripts & Jquery ======-->
<script src="<?php echo base_url("assets/js/jquery-3.2.1.min.js"); ?>"></script>
    <script src="<?php echo base_url("assets/js/bootstrap.min.js"); ?>"></script>
    <script src="<?php echo base_url("assets/js/jquery.slicknav.min.js"); ?>"></script>
    <script src="<?php echo base_url("assets/js/owl.carousel.min.js"); ?>"></script>
    <script src="<?php echo base_url("assets/js/jquery.nicescroll.min.js"); ?>"></script>
    <script src="<?php echo base_url("assets/js/jquery.zoom.min.js"); ?>"></script>
    <script src="<?php echo base_url("assets/js/jquery-ui.min.js"); ?>"></script>
    <script src="<?php echo base_url("assets/js/main.js"); ?>"></script>